name: Pull Request Action
on: create
      
jobs:
  open-pull-request:
    if: ${{ github.event.ref_type != 'tag' && github.actor != 'dependabot[bot]'}}
    runs-on: ubuntu-latest
    permissions: 
        contents: read
        issues: write
        pull-requests: write
        id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract commit title
        id: extract_commit_title
        run: echo "::set-output name=title::$(git log -1 --pretty=%s)"

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GHA_PAT }}
          script: |
            const { repo, owner } = context.repo;
            const title = "${{ steps.extract_commit_title.outputs.title }}";
            const result = await github.rest.pulls.create({
              title: title,
              owner,
              repo,
              head: '${{ github.ref }}',
              base: 'main',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['feature', 'automated pr']
            });