name: 📎 Docker Build and Push on Release

on:
  release:
    types: [created]

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Extract Tag Name
      id: tag_name
      run: echo "::set-output name=TAG_NAME::$(echo ${GITHUB_REF#refs/tags/})"

    - name: Build Docker Image
      run: docker build -t wecontrib-dev:${{ steps.tag_name.outputs.TAG_NAME }} .

    - name: Tag Docker Image
      run: docker tag wecontrib-dev:${{ steps.tag_name.outputs.TAG_NAME }} ${{ vars.DOCKER_HUB_USERNAME }}/wecontrib-dev:${{ steps.tag_name.outputs.TAG_NAME }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Docker Image
      run: docker push ${{ vars.DOCKER_HUB_USERNAME }}/wecontrib-dev:${{ steps.tag_name.outputs.TAG_NAME }}
